/**
 * Development Orchestrator - Manages software development phase
 * Uses the same agents that created the PRD to build the software
 */

import type {
    Agent,
    AgentResponse,
    PRDState,
    DevelopmentState,
    CodeFile,
} from '@/lib/types/agent-types';
import { developmentAgents, getAgentByRole } from '@/lib/agents/agent-config';
import { getVertexAIClient } from '@/lib/ai/vertex-client';

export class DevelopmentOrchestrator {
    private agents: Agent[];
    private developmentState: DevelopmentState;
    private prdState: PRDState;

    constructor(prdState: PRDState) {
        this.agents = developmentAgents;
        this.prdState = prdState;
        this.developmentState = this.initializeDevelopmentState();
    }

    /**
     * Initialize empty development state
     */
    private initializeDevelopmentState(): DevelopmentState {
        return {
            files: [],
            currentPhase: 'planning',
            completedTasks: [],
            pendingTasks: [],
            issues: [],
        };
    }

    /**
     * Phase 1: Planning - Break down PRD into actionable tasks
     */
    async planDevelopment(): Promise<{
        tasks: string[];
        architecture: string;
    }> {
        const planningAgent = getAgentByRole('planning');
        if (!planningAgent) throw new Error('Planning agent not found');

        const client = getVertexAIClient();

        const prompt = `Based on this PRD, create a detailed development plan:

${JSON.stringify(this.prdState, null, 2)}

Provide:
1. List of development tasks in priority order
2. High-level architecture overview
3. Suggested tech stack
4. File structure

Format as JSON:
{
  "tasks": ["task 1", "task 2", ...],
  "architecture": "architecture description",
  "techStack": {...},
  "fileStructure": {...}
}`;

        try {
            const response = await client.generateJSON<{
                tasks: string[];
                architecture: string;
                techStack: Record<string, string>;
                fileStructure: Record<string, string[]>;
            }>(prompt, planningAgent.systemPrompt);

            this.developmentState.pendingTasks = response.tasks;
            this.developmentState.currentPhase = 'implementation';

            return {
                tasks: response.tasks,
                architecture: response.architecture,
            };
        } catch (error) {
            console.error('Error planning development:', error);
            throw error;
        }
    }

    /**
     * Phase 2: Implementation - Generate code files
     */
    async generateCode(filePath: string, description: string): Promise<CodeFile> {
        // Determine which agent should handle this file
        const agent = this.selectAgentForFile(filePath);
        const client = getVertexAIClient();

        const prompt = `Create the file: ${filePath}

Description: ${description}

PRD Context:
${JSON.stringify(this.prdState, null, 2)}

Existing Files:
${this.developmentState.files.map(f => `- ${f.path}`).join('\n')}

Generate the complete, production-ready code for this file.
Return ONLY the code content, no explanations.`;

        try {
            const content = await client.generate(prompt, agent.systemPrompt);

            const codeFile: CodeFile = {
                path: filePath,
                content: this.cleanCodeResponse(content),
                language: this.detectLanguage(filePath),
                generatedBy: agent.role,
            };

            this.developmentState.files.push(codeFile);

            return codeFile;
        } catch (error) {
            console.error(`Error generating code for ${filePath}:`, error);
            throw error;
        }
    }

    /**
     * Phase 3: Testing - Run tests and identify issues
     */
    async runTests(): Promise<{
        passed: boolean;
        results: string[];
        issues: string[];
    }> {
        const testingAgent = getAgentByRole('testing');
        if (!testingAgent) throw new Error('Testing agent not found');

        const client = getVertexAIClient();

        const prompt = `Analyze this codebase for issues and suggest tests:

PRD:
${JSON.stringify(this.prdState, null, 2)}

Generated Files:
${this.developmentState.files.map(f => `
File: ${f.path}
Generated by: ${f.generatedBy}
Content (first 500 chars):
${f.content.substring(0, 500)}...
`).join('\n---\n')}

Provide:
1. List of issues found
2. Suggested tests to write
3. Overall quality assessment

Format as JSON:
{
  "issues": ["issue 1", "issue 2", ...],
  "suggestedTests": ["test 1", "test 2", ...],
  "quality": "assessment"
}`;

        try {
            const response = await client.generateJSON<{
                issues: string[];
                suggestedTests: string[];
                quality: string;
            }>(prompt, testingAgent.systemPrompt);

            // Add issues to development state
            response.issues.forEach(issue => {
                this.developmentState.issues.push({
                    id: `issue-${Date.now()}-${Math.random()}`,
                    description: issue,
                    severity: 'medium',
                    assignedTo: 'backend', // Default, can be smarter
                    status: 'open',
                });
            });

            return {
                passed: response.issues.length === 0,
                results: response.suggestedTests,
                issues: response.issues,
            };
        } catch (error) {
            console.error('Error running tests:', error);
            throw error;
        }
    }

    /**
     * Phase 4: Deployment - Prepare deployment configuration
     */
    async prepareDeployment(): Promise<{
        platform: string;
        config: Record<string, any>;
        steps: string[];
    }> {
        const deploymentAgent = getAgentByRole('deployment');
        if (!deploymentAgent) throw new Error('Deployment agent not found');

        const client = getVertexAIClient();

        const prompt = `Create deployment configuration for this project:

PRD:
${JSON.stringify(this.prdState, null, 2)}

Tech Stack:
${this.inferTechStack()}

Provide:
1. Recommended deployment platform (Vercel, Netlify, AWS, GCP, etc.)
2. Configuration files needed
3. Deployment steps

Format as JSON:
{
  "platform": "platform name",
  "config": {...},
  "steps": ["step 1", "step 2", ...]
}`;

        try {
            const response = await client.generateJSON<{
                platform: string;
                config: Record<string, any>;
                steps: string[];
            }>(prompt, deploymentAgent.systemPrompt);

            return response;
        } catch (error) {
            console.error('Error preparing deployment:', error);
            throw error;
        }
    }

    /**
     * Get development state
     */
    getDevelopmentState(): DevelopmentState {
        return { ...this.developmentState };
    }

    /**
     * Get specific file
     */
    getFile(path: string): CodeFile | undefined {
        return this.developmentState.files.find(f => f.path === path);
    }

    /**
     * Get all files
     */
    getAllFiles(): CodeFile[] {
        return [...this.developmentState.files];
    }

    /**
     * Helper: Select appropriate agent for a file
     */
    private selectAgentForFile(filePath: string): Agent {
        const path = filePath.toLowerCase();

        if (path.includes('component') || path.includes('.tsx') || path.includes('.jsx')) {
            return getAgentByRole('frontend') || this.agents[0];
        }
        if (path.includes('api') || path.includes('server') || path.includes('backend')) {
            return getAgentByRole('backend') || this.agents[0];
        }
        if (path.includes('style') || path.includes('.css') || path.includes('design')) {
            return getAgentByRole('ux') || this.agents[0];
        }
        if (path.includes('database') || path.includes('schema') || path.includes('migration')) {
            return getAgentByRole('database') || this.agents[0];
        }
        if (path.includes('test')) {
            return getAgentByRole('testing') || this.agents[0];
        }

        // Default to planning agent for config files
        return getAgentByRole('planning') || this.agents[0];
    }

    /**
     * Helper: Clean code response (remove markdown, explanations)
     */
    private cleanCodeResponse(response: string): string {
        // Remove markdown code blocks
        let cleaned = response.replace(/```[\w]*\n?/g, '');

        // Remove common explanatory text patterns
        cleaned = cleaned.replace(/^Here'?s? (?:the|a) .*?:\s*/gim, '');
        cleaned = cleaned.replace(/^This (?:code|file) .*?:\s*/gim, '');

        return cleaned.trim();
    }

    /**
     * Helper: Detect programming language from file path
     */
    private detectLanguage(filePath: string): string {
        const ext = filePath.split('.').pop()?.toLowerCase();
        const langMap: Record<string, string> = {
            'ts': 'typescript',
            'tsx': 'typescript',
            'js': 'javascript',
            'jsx': 'javascript',
            'py': 'python',
            'json': 'json',
            'css': 'css',
            'html': 'html',
            'md': 'markdown',
        };
        return langMap[ext || ''] || 'text';
    }

    /**
     * Helper: Infer tech stack from generated files
     */
    private inferTechStack(): string {
        const files = this.developmentState.files;
        const hasTsx = files.some(f => f.path.endsWith('.tsx'));
        const hasNext = files.some(f => f.path.includes('next.config'));
        const hasPython = files.some(f => f.path.endsWith('.py'));

        let stack = [];
        if (hasTsx) stack.push('TypeScript', 'React');
        if (hasNext) stack.push('Next.js');
        if (hasPython) stack.push('Python');

        return stack.join(', ') || 'Unknown';
    }
}
