from docx import Document
from tools.normalize_prd import normalize_prd

PRD_SECTIONS = [
    ("Introduction",            "introduction"),
    ("Customer Needs / Market / Business Model", "customer_needs"),
    ("Known Customers & Requests",      "known_requests"),
    ("Quantitative Customer Data",      "customer_data"),
    ("Business Model & Pricing",        "business_model"),
    ("Expected Results",       "expected_results"),
    ("Marketing & Communication",       "marketing_plan"),
    ("Key Metrics",            "metrics"),
    ("Terms & Copy",           "terms"),
    ("Personas",               "personas"),
    ("Functional Requirements","features"),
    ("Non‑Functional Requirements","non_functional"),
    ("Design Notes",           "design_notes"),
    ("Technical Specifications","technical_specs"),
]

def generate_prd_docx(title, history, prd_state):
    prd_state = normalize_prd(prd_state)
    doc = Document()

    # Title
    doc.add_heading(f"PRD: {title}", level=0)
    doc.add_heading("Changelog", level=1)
    doc.add_paragraph("Auto-generated by ProductHive.\n")

    doc.add_heading("Related Documents", level=1)
    doc.add_paragraph("")  # you can insert links here

    # Loop through each section, handling lists vs strings
    for heading, key in PRD_SECTIONS:
        content = prd_state.get(key, None)
        doc.add_heading(heading, level=1)

        if isinstance(content, list):
            if content:
                for item in content:
                    doc.add_paragraph(item, style="List Bullet")
            else:
                doc.add_paragraph("(No entries)")
        else:
            text = str(content or "").strip()
            if text:
                for line in text.split("\n"):
                    doc.add_paragraph(line)
            else:
                doc.add_paragraph("(No entries)")

    return doc
